In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('SubmissionBeit_random_1.csv')
df1 = df1.rename(columns={'Label':'Label_1'})

df2 = pd.read_csv('SubmissionBeit_random_2.csv')
df2 = df2.rename(columns={'Label':'Label_2'})

df3 = pd.read_csv('SubmissionBeit_random_3.csv')
df3 = df3.rename(columns={'Label':'Label_3'})

df4 = pd.read_csv('SubmissionBeit_random_4.csv')
df4 = df4.rename(columns={'Label':'Label_4'})

df5 = pd.read_csv('SubmissionBeit_random_5.csv')
df5 = df5.rename(columns={'Label':'Label_5'})

In [3]:
df_combined = df1.merge(df2)
df_combined = df_combined.merge(df3)
df_combined = df_combined.merge(df4)
df_combined = df_combined.merge(df5)
df_combined[df_combined['Label_1'] !=df_combined['Label_2'] ]

          ID    Label_1      Label_2    Label_3      Label_4      Label_5
29        29       dogs         cats       dogs         dogs         dogs
63        63      lions    elephants  elephants        lions    elephants
96        96     fishes        vases      vases        vases        vases
152      152       cats         dogs       cats         cats         dogs
179      179     fishes        vases      vases        vases        vases
...      ...        ...          ...        ...          ...          ...
16033  16033      vases        birds    bottles        birds        birds
16038  16038       cows      bottles     horses      bottles        vases
16055  16055  elephants       horses  elephants    elephants       horses
16088  16088    spiders       fishes     breads       breads        vases
16162  16162    spiders  butterflies    spiders  butterflies  butterflies

[348 rows x 6 columns]

In [18]:
import pandas as pd


def majority_vote(row):
    labels = [row["Label_1"], row["Label_2"], row["Label_3"]]#, row["Label_4"], row["Label_5"]]
    counts = pd.Series(labels).value_counts()
    top_count = counts.max()
    winners = counts[counts == top_count].index.tolist()
    
    if len(winners) == 1:
        return winners[0]       # clear winner
    else:
        return row["Label_1"]   # tie-breaker

df_combined["final_label"] = df_combined.apply(majority_vote, axis=1)
print(df_combined)

          ID      Label_1      Label_2      Label_3  final_label
0          0         dogs         dogs         dogs         dogs
1          1     handguns     handguns     handguns     handguns
2          2        seals        seals        seals        seals
3          3         dogs         dogs         dogs         dogs
4          4  butterflies  butterflies  butterflies  butterflies
...      ...          ...          ...          ...          ...
16162  16162      spiders      spiders  butterflies      spiders
16163  16163      spiders      spiders      spiders      spiders
16164  16164        ducks        ducks        ducks        ducks
16165  16165        ducks        ducks        ducks        ducks
16166  16166      spiders      spiders      spiders      spiders

[16167 rows x 5 columns]

In [19]:
df_combined

          ID      Label_1      Label_2      Label_3  final_label
0          0         dogs         dogs         dogs         dogs
1          1     handguns     handguns     handguns     handguns
2          2        seals        seals        seals        seals
3          3         dogs         dogs         dogs         dogs
4          4  butterflies  butterflies  butterflies  butterflies
...      ...          ...          ...          ...          ...
16162  16162      spiders      spiders  butterflies      spiders
16163  16163      spiders      spiders      spiders      spiders
16164  16164        ducks        ducks        ducks        ducks
16165  16165        ducks        ducks        ducks        ducks
16166  16166      spiders      spiders      spiders      spiders

[16167 rows x 5 columns]

In [20]:
df_final = df_combined[['ID','final_label']]

df_final = df_final.rename(columns={'final_label':'Label'})

In [21]:
df_final.to_csv('First Ensemble.csv', index=False)

In [22]:
df1 = pd.read_csv('SubmissionDino_random_1_Large.csv')
df1 = df1.rename(columns={'Label':'Label_1'})

df2 = pd.read_csv('SubmissionDino_random_1_giant.csv')
df2 = df2.rename(columns={'Label':'Label_2'})

df3 = pd.read_csv('SubmissionDino_random_2_Large.csv')
df3 = df3.rename(columns={'Label':'Label_3'})

#df4 = pd.read_csv('SubmissionDino_random_2_Large')
#df4 = df4.rename(columns={'Label':'Label_4'})

#df5 = pd.read_csv('SubmissionBeit_random_5.csv')
#df5 = df5.rename(columns={'Label':'Label_5'})
df2

          ID      Label_2
0          0         dogs
1          1     handguns
2          2        seals
3          3         dogs
4          4  butterflies
...      ...          ...
16162  16162      spiders
16163  16163      spiders
16164  16164        ducks
16165  16165        ducks
16166  16166      spiders

[16167 rows x 2 columns]

In [23]:
df_combined = df1.merge(df2)
df_combined = df_combined.merge(df3)
df_combined["final_label"] = df_combined.apply(majority_vote, axis=1)
df_combined

          ID      Label_1      Label_2      Label_3  final_label
0          0         dogs         dogs         dogs         dogs
1          1     handguns     handguns     handguns     handguns
2          2        seals        seals        seals        seals
3          3         dogs         dogs         dogs         dogs
4          4  butterflies  butterflies  butterflies  butterflies
...      ...          ...          ...          ...          ...
16162  16162      spiders      spiders  butterflies      spiders
16163  16163      spiders      spiders      spiders      spiders
16164  16164        ducks        ducks        ducks        ducks
16165  16165        ducks        ducks        ducks        ducks
16166  16166      spiders      spiders      spiders      spiders

[16167 rows x 5 columns]

In [25]:
df_final_dino = df_combined[['ID','final_label']]

df_final_dino = df_final_dino.rename(columns={'final_label':'Label'})
df_final.to_csv('Dino First Ensemble.csv', index=False)

In [10]:
df1 = pd.read_csv('Submission_Register_Dino_Random_Large_3.csv')
df1 = df1.rename(columns={'Label':'Label_1'})

df2 = pd.read_csv('Submission_Giant_Register.csv')
df2 = df2.rename(columns={'Label':'Label_2'})

df3 = pd.read_csv('Register_Dino_Random_Giant_seed77_train0.8_aug1_epoch20.csv')
df3 = df3.rename(columns={'Label':'Label_3'})

df_combined = df1.merge(df2)
df_combined = df_combined.merge(df3)
df_combined["final_label"] = df_combined.apply(majority_vote, axis=1)
df_combined

          ID      Label_1      Label_2      Label_3  final_label
0          0         dogs         dogs         dogs         dogs
1          1     handguns     handguns     handguns     handguns
2          2        seals        seals        seals        seals
3          3         dogs         dogs         dogs         dogs
4          4  butterflies  butterflies  butterflies  butterflies
...      ...          ...          ...          ...          ...
16162  16162      spiders      spiders      spiders      spiders
16163  16163      spiders      spiders      spiders      spiders
16164  16164        ducks        ducks        ducks        ducks
16165  16165        ducks        ducks        ducks        ducks
16166  16166      spiders      spiders      spiders      spiders

[16167 rows x 5 columns]

In [11]:
import pandas as pd


def majority_vote(row):
    labels = [row["Label_1"], row["Label_2"], row["Label_3"]]#, row["Label_4"], row["Label_5"]]
    counts = pd.Series(labels).value_counts()
    top_count = counts.max()
    winners = counts[counts == top_count].index.tolist()
    
    if len(winners) == 1:
        return winners[0]       # clear winner
    else:
        return row["Label_1"]   # tie-breaker

df_combined["final_label"] = df_combined.apply(majority_vote, axis=1)
df_combined

          ID      Label_1      Label_2      Label_3  final_label
0          0         dogs         dogs         dogs         dogs
1          1     handguns     handguns     handguns     handguns
2          2        seals        seals        seals        seals
3          3         dogs         dogs         dogs         dogs
4          4  butterflies  butterflies  butterflies  butterflies
...      ...          ...          ...          ...          ...
16162  16162      spiders      spiders      spiders      spiders
16163  16163      spiders      spiders      spiders      spiders
16164  16164        ducks        ducks        ducks        ducks
16165  16165        ducks        ducks        ducks        ducks
16166  16166      spiders      spiders      spiders      spiders

[16167 rows x 5 columns]

In [12]:
df_combined[df_combined['Label_1']!=df_combined['final_label']]

          ID      Label_1      Label_2      Label_3  final_label
1167    1167    elephants         cows         cows         cows
1988    1988     chickens        ducks        ducks        ducks
2282    2282       breads         dogs         dogs         dogs
2560    2560         cows       snakes       snakes       snakes
3370    3370    lipsticks        vases        vases        vases
3570    3570       fishes  butterflies  butterflies  butterflies
4167    4167      bottles        vases        vases        vases
5044    5044        vases      bottles      bottles      bottles
5587    5587     chickens        ducks        ducks        ducks
5612    5612     chickens        ducks        ducks        ducks
5681    5681         cats         dogs         dogs         dogs
5717    5717    lipsticks        vases        vases        vases
6256    6256        cakes       breads       breads       breads
6577    6577        vases      bottles      bottles      bottles
6632    6632  butterflies      spiders      spiders      spiders
7565    7565  butterflies       snakes       snakes       snakes
8504    8504  butterflies    lipsticks    lipsticks    lipsticks
8666    8666     chickens        ducks        ducks        ducks
9350    9350     chickens  butterflies  butterflies  butterflies
9999    9999      bottles         cats         cats         cats
10670  10670         cows    elephants    elephants    elephants
10679  10679     chickens        ducks        ducks        ducks
11055  11055        lions    elephants    elephants    elephants
11359  11359         cows       horses       horses       horses
12597  12597        ducks         dogs         dogs         dogs
12639  12639     handguns    lipsticks    lipsticks    lipsticks
13808  13808      bottles        ducks        ducks        ducks
13936  13936  butterflies      spiders      spiders      spiders
14147  14147         cows    elephants    elephants    elephants
14527  14527     handguns      bottles      bottles      bottles
14610  14610  butterflies      spiders      spiders      spiders
15723  15723     handguns       horses       horses       horses
16115  16115       fishes  butterflies  butterflies  butterflies

In [13]:
df_final = df_combined[['ID','final_label']]

df_final = df_final.rename(columns={'final_label':'Label'})
df_final.to_csv('Second Giant Ensemble.csv', index=False)